services:
  db:
    container_name: db
    image: postgres:16.1
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: streaming-platform
      POSTGRES_PASSWORD: streaming-platform
      POSTGRES_DB: streaming-platform
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
  api:
    container_name: api
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    command: api
    env_file:
      - .env
  worker:
    container_name: worker
    build: .
    restart: always
    depends_on:
      - redis
    command: worker
    env_file:
      - .env
