services:
  db:
    container_name: db
    image: postgres:16.1
    restart: always
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: streaming-platform
      POSTGRES_PASSWORD: streaming-platform
      POSTGRES_DB: streaming-platform
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
